import type { FlightData } from "../../type/FlightData.ts";

export const FLIGTHS_DATA: FlightData[] = [
  {
    flightNumber: "RN7480",
    airline: "Ryanair",
    airlineIconUrl: "https://logo.clearbit.com/ryanair.com",
    aircraftImageUrl: "/aircrafts/ryanair-737max.png",
    aircraftReg: "D-MNOP",
    from: {
      code: "DUB",
      city: "Dublin",
      timezone: "UTC+0",
    },
    to: {
      code: "FRA",
      city: "Frankfurt",
      timezone: "UTC+1",
    },
    progress: {
      totalDistanceKm: 3811,
      totalDuration: "4h 22m",
      completedDistanceKm: 3217,
      completedDuration: "3h 40m",
    },
    schedule: {
      departure: {
        planned: "09:29",
        actual: "22:47",
      },
      arrival: {
        planned: "21:07",
        estimated: "08:08",
      },
    },
    aircraft: {
      model: "Boeing 737-800",
      country: "Ryanair",
      countryFlag: "🇮🇪",
    },
    speed: "863 km/h",
    altitude: "11270 m",
  },
  {
    flightNumber: "LH1234",
    airline: "Lufthansa",
    airlineIconUrl: "https://logo.clearbit.com/lufthansa.com",
    aircraftImageUrl: "/aircrafts/lufthansa-737max.png",
    aircraftReg: "D-AILU",
    from: { code: "FRA", city: "Frankfurt", timezone: "UTC+1" },
    to: { code: "JFK", city: "New York", timezone: "UTC-5" },
    progress: {
      totalDistanceKm: 6200,
      totalDuration: "8h 45m",
      completedDistanceKm: 4100,
      completedDuration: "5h 47m",
    },
    schedule: {
      departure: { planned: "10:00", actual: "10:12" },
      arrival: { planned: "18:45", estimated: "18:50" },
    },
    aircraft: {
      model: "Airbus A320",
      country: "Germany",
      countryFlag: "🇩🇪",
    },
    speed: "890 km/h",
    altitude: "11 000 m",
  },
  {
    flightNumber: "AF452",
    airline: "Air France",
    airlineIconUrl: "https://logo.clearbit.com/airfrance.com",
    aircraftImageUrl: "/aircrafts/air-france.png",
    aircraftReg: "F-GSQI",
    from: { code: "CDG", city: "Paris", timezone: "UTC+1" },
    to: { code: "GRU", city: "São Paulo", timezone: "UTC-3" },
    progress: {
      totalDistanceKm: 9400,
      totalDuration: "11h 15m",
      completedDistanceKm: 7800,
      completedDuration: "9h 22m",
    },
    schedule: {
      departure: { planned: "23:00", actual: "23:07" },
      arrival: { planned: "06:15", estimated: "06:20" },
    },
    aircraft: {
      model: "Boeing 777",
      country: "France",
      countryFlag: "🇫🇷",
    },
    speed: "920 km/h",
    altitude: "11 500 m",
  },
  {
    flightNumber: "AC789",
    airline: "Air Canada",
    airlineIconUrl: "https://logo.clearbit.com/aircanada.com",
    aircraftImageUrl: "/aircrafts/air-canada.png",
    aircraftReg: "C-GHPU",
    from: { code: "YYZ", city: "Toronto", timezone: "UTC-5" },
    to: { code: "YVR", city: "Vancouver", timezone: "UTC-8" },
    progress: {
      totalDistanceKm: 3350,
      totalDuration: "4h 55m",
      completedDistanceKm: 1770,
      completedDuration: "2h 32m",
    },
    schedule: {
      departure: { planned: "14:00", actual: "14:09" },
      arrival: { planned: "18:55", estimated: "19:05" },
    },
    aircraft: {
      model: "Boeing 787 Dreamliner",
      country: "Canada",
      countryFlag: "🇨🇦",
    },
    speed: "860 km/h",
    altitude: "12 000 m",
  },
  {
    flightNumber: "AZ610",
    airline: "ITA Airways",
    airlineIconUrl: "https://logo.clearbit.com/ita-airways.com",
    aircraftImageUrl: "/aircrafts/ita-airways.png",
    aircraftReg: "EI-DIR",
    from: { code: "FCO", city: "Rome", timezone: "UTC+1" },
    to: { code: "JFK", city: "New York", timezone: "UTC-5" },
    progress: {
      totalDistanceKm: 7000,
      totalDuration: "9h 10m",
      completedDistanceKm: 5900,
      completedDuration: "7h 40m",
    },
    schedule: {
      departure: { planned: "09:15", actual: "09:21" },
      arrival: { planned: "13:25", estimated: "13:31" },
    },
    aircraft: {
      model: "Airbus A330",
      country: "Italy",
      countryFlag: "🇮🇹",
    },
    speed: "880 km/h",
    altitude: "11 700 m",
  },
  {
    flightNumber: "SU100",
    airline: "Aeroflot",
    airlineIconUrl: "https://logo.clearbit.com/aeroflot.ru",
    aircraftImageUrl: "/aircrafts/aeroflot.png",
    aircraftReg: "RA-89012",
    from: { code: "SVO", city: "Moscow", timezone: "UTC+3" },
    to: { code: "LED", city: "Saint Petersburg", timezone: "UTC+3" },
    progress: {
      totalDistanceKm: 700,
      totalDuration: "1h 20m",
      completedDistanceKm: 510,
      completedDuration: "0h 58m",
    },
    schedule: {
      departure: { planned: "17:00", actual: "17:05" },
      arrival: { planned: "18:20", estimated: "18:22" },
    },
    aircraft: {
      model: "Sukhoi Superjet 100",
      country: "Russia",
      countryFlag: "🇷🇺",
    },
    speed: "750 km/h",
    altitude: "10 300 m",
  },
  {
    flightNumber: "QR202",
    airline: "Qatar Airways",
    airlineIconUrl: "https://logo.clearbit.com/qatarairways.com",
    aircraftImageUrl: "/aircrafts/qatar-airways.png",
    aircraftReg: "A7-ALC",
    from: { code: "DOH", city: "Doha", timezone: "UTC+3" },
    to: { code: "SYD", city: "Sydney", timezone: "UTC+11" },
    progress: {
      totalDistanceKm: 12100,
      totalDuration: "14h 45m",
      completedDistanceKm: 10020,
      completedDuration: "12h 10m",
    },
    schedule: {
      departure: { planned: "02:00", actual: "02:15" },
      arrival: { planned: "20:45", estimated: "21:00" },
    },
    aircraft: {
      model: "Airbus A350",
      country: "Qatar",
      countryFlag: "🇶🇦",
    },
    speed: "905 km/h",
    altitude: "12 300 m",
  },
  {
    flightNumber: "EK015",
    airline: "Emirates",
    airlineIconUrl: "https://logo.clearbit.com/emirates.com",
    aircraftImageUrl: "/aircrafts/emirates.png",
    aircraftReg: "A6-EDZ",
    from: { code: "DXB", city: "Dubai", timezone: "UTC+4" },
    to: { code: "LHR", city: "London", timezone: "UTC+0" },
    progress: {
      totalDistanceKm: 5500,
      totalDuration: "7h 05m",
      completedDistanceKm: 4920,
      completedDuration: "6h 18m",
    },
    schedule: {
      departure: { planned: "07:45", actual: "07:53" },
      arrival: { planned: "12:50", estimated: "12:58" },
    },
    aircraft: {
      model: "Airbus A380",
      country: "UAE",
      countryFlag: "🇦🇪",
    },
    speed: "890 km/h",
    altitude: "11 800 m",
  },
  {
    flightNumber: "JL002",
    airline: "Japan Airlines",
    airlineIconUrl: "https://logo.clearbit.com/jal.com",
    aircraftImageUrl: "/aircrafts/japan-airlines.png",
    aircraftReg: "JA832J",
    from: { code: "HND", city: "Tokyo", timezone: "UTC+9" },
    to: { code: "LAX", city: "Los Angeles", timezone: "UTC-8" },
    progress: {
      totalDistanceKm: 8800,
      totalDuration: "10h 40m",
      completedDistanceKm: 7120,
      completedDuration: "8h 42m",
    },
    schedule: {
      departure: { planned: "18:00", actual: "18:05" },
      arrival: { planned: "10:40", estimated: "10:45" },
    },
    aircraft: {
      model: "Boeing 787",
      country: "Japan",
      countryFlag: "🇯🇵",
    },
    speed: "880 km/h",
    altitude: "11 600 m",
  },
  {
    flightNumber: "UA459",
    airline: "United Airlines",
    airlineIconUrl: "https://logo.clearbit.com/united.com",
    aircraftImageUrl: "/aircrafts/united-airlines.png",
    aircraftReg: "N37277",
    from: { code: "ORD", city: "Chicago", timezone: "UTC-6" },
    to: { code: "DEN", city: "Denver", timezone: "UTC-7" },
    progress: {
      totalDistanceKm: 1420,
      totalDuration: "2h 20m",
      completedDistanceKm: 650,
      completedDuration: "1h 02m",
    },
    schedule: {
      departure: { planned: "13:45", actual: "13:49" },
      arrival: { planned: "16:05", estimated: "16:10" },
    },
    aircraft: {
      model: "Boeing 737 MAX 8",
      country: "USA",
      countryFlag: "🇺🇸",
    },
    speed: "845 km/h",
    altitude: "10 900 m",
  },
  {
    flightNumber: "NZ3",
    airline: "Air New Zealand",
    airlineIconUrl: "https://logo.clearbit.com/airnewzealand.com",
    aircraftImageUrl: "/aircrafts/air-ew-zealand.png",
    aircraftReg: "ZK-OKN",
    from: { code: "AKL", city: "Auckland", timezone: "UTC+13" },
    to: { code: "LAX", city: "Los Angeles", timezone: "UTC-8" },
    progress: {
      totalDistanceKm: 10500,
      totalDuration: "12h 30m",
      completedDistanceKm: 9920,
      completedDuration: "11h 48m",
    },
    schedule: {
      departure: { planned: "21:00", actual: "21:15" },
      arrival: { planned: "09:30", estimated: "09:40" },
    },
    aircraft: {
      model: "Boeing 777",
      country: "New Zealand",
      countryFlag: "🇳🇿",
    },
    speed: "900 km/h",
    altitude: "11 700 m",
  },
];
